fx_version 'cerulean'
game 'gta5'

author 'Vcore'
description 'FxManifest Generated by VCore, All Files Sorted and Ready for Exicution <Replace with Your Resource Description>'
version '1.0.0'

client_scripts {
    'client/client.lua'
}

server_scripts {
    'server/server.lua'
}

ui_page     'html/index.html'

files {
    'html/index.html',
    'html/scripts.js',
    'html/styles.css'
}
